In [1]:
import pandas as pd
from datetime import date

In [2]:
today = date.today()
today_str = today.strftime("%Y%m%d")
print(today_str)

20180530

In [3]:
this_yearterm = "2018.Fall"
last_yearterm = "2017.Fall"
twoyrago_yearterm = "2016.Fall"

In [4]:
df = pd.read_hdf("X:/Applications/Admissions/funnel/data/stage_data", key="weekly")
df = df.loc[df["year_term"].isin([this_yearterm, last_yearterm, twoyrago_yearterm])]

In [5]:
def adm_week(d):
    """
    returns calendar week number and Admissions Week Number for a given date, d
    """
    year = d.year
    if d >= date(year, 9, 1):
        adm_year_start = year
    else:
        adm_year_start = year - 1

    week_number = d.isocalendar()[1]
    adm_start_week = date(adm_year_start, 9, 1).isocalendar()[1]

    if week_number >= adm_start_week:
        adm_week_number = week_number - adm_start_week
    else:
        adm_week_number = 53 + (week_number - adm_start_week)

    return (week_number, adm_week_number)

In [6]:
week_number, adm_week_number = adm_week(today)
week = adm_week(today)[1]

In [7]:
print(str(week))

40

In [8]:
df["curriculum"] = df["curriculum"].fillna("unknown")
summ = df.groupby(["year_term", "stage", "curriculum"]).sum()
# summ_t = summ.transpose()

In [9]:
print(summ.shape)
summ.head()

(240, 54)

                               00  01  02  03  04  05  06  07  08  09 ...  44  \
year_term stage    curriculum                                         ...
2016.Fall Accepted AALM         0   0   0   0   0   0   0   0   0   0 ...   9
                   BAKA         0   0   0   0   0   0   0   0   0   0 ...  11
                   BASM         0   0   0   0   0   0   0   0   0   0 ...  15
                   BIOG         1   1   1   1   1   1   1   1   1   1 ...  11
                   CASM         0   0   0   0   0   0   0   0   0   0 ...  12

                               45  46  47  48  49  50  51  52  53
year_term stage    curriculum
2016.Fall Accepted AALM         9   9   9   9   9   9   9   9   9
                   BAKA        11  11  11  11  11  11  11  11  11
                   BASM        15  15  15  15  15  15  15  15  15
                   BIOG        11  11  11  11  11  11  11  11  11
                   CASM        12  12  12  12  11  12  12  12  12

[5 rows x 54 columns]

In [ ]:
summ_t.head()

In [10]:
df.loc[(df["year_term"] == "2017.Fall") & (df["stage"] == "Deposited")]["40"].sum()

219

In [11]:
t = df.loc[(df["year_term"] == "2017.Fall") & (df["stage"] == "Deposited")][
    ["curriculum", "40"]
]
t["curriculum"] = t["curriculum"].fillna("unknown")
t.groupby(["curriculum"]).sum()

            40
curriculum
AALM         5
BAKA         5
BASM         7
BIOG         3
CASM        10
COMM         1
CULA         4
EBSB         5
ECOR         5
ENST         2
ENVS        21
FEFM        16
FFOP         7
FORT         2
FWSF        13
FWSW        39
HRMT         1
HRTM         6
INST         2
NRCM        20
PACM         8
RECR         9
SCWL         2
SURV         6
UNDM         0
unknown     20

In [12]:
t.groupby(["curriculum"]).sum().shape

(26, 1)

In [13]:
t = df.loc[(df["year_term"] == "2018.Fall") & (df["stage"] == "Deposited")][
    ["curriculum", "40"]
]
t["curriculum"] = t["curriculum"].fillna("unknown")
t.groupby(["curriculum"]).sum()

            40
curriculum
AALM         5
BAKA         3
BASM         7
BIOG         5
CASM        10
COMM         3
CULO         3
EBSB         5
ECOR         7
ENST         3
ENVS        21
FBIO         1
FEFM        10
FFOP         8
FORT         4
FWSF         9
FWSW        40
HRMT         1
HRTM         3
INST         2
NRCM        30
PACM        11
PSYCH        1
RECR         7
SCWL         2
SURV         4
unknown      0

In [14]:
t.groupby(["curriculum"]).sum().shape

(27, 1)

In [15]:
summ.loc[("2017.Fall", "Deposited")][str(week)].sum()

219

In [16]:
summ.loc[("2017.Fall", "Deposited")][str(week)]

curriculum
AALM        5
BAKA        5
BASM        7
BIOG        3
CASM       10
COMM        1
CULA        4
EBSB        5
ECOR        5
ENST        2
ENVS       21
FEFM       16
FFOP        7
FORT        2
FWSF       13
FWSW       39
HRMT        1
HRTM        6
INST        2
NRCM       20
PACM        8
RECR        9
SCWL        2
SURV        6
UNDM        0
unknown    20
Name: 40, dtype: int64

In [ ]:
stage = "Deposited"
plot_df = pd.DataFrame({this_yearterm: summ.loc[(this_yearterm, stage)][str(week)]})
print(plot_df.shape)
print(plot_df.head())
print(plot_df.info())
print(pd.DataFrame({last_yearterm: summ.loc[(last_yearterm, stage)][str(week)]}).info())
plot_df = (
    pd.concat(
        [
            plot_df,
            pd.DataFrame({last_yearterm: summ.loc[(last_yearterm, stage)][str(week)]}),
        ],
        axis=1,
        sort=True,
    )
    .fillna(0)
    .astype(int)
)
print(plot_df.shape)
print(plot_df)
plot_df.head()

In [14]:
tab_df = pd.DataFrame(
    {this_yearterm + "_Week" + str(week): summ.loc[(this_yearterm,)][str(week)]}
)
tab_df = pd.concat(
    [
        tab_df,
        pd.DataFrame(
            {last_yearterm + "_Week" + str(week): summ.loc[(last_yearterm,)][str(week)]}
        ),
    ],
    axis=1,
    sort=True,
)
tab_df = pd.concat(
    [
        tab_df,
        pd.DataFrame(
            {
                twoyrago_yearterm
                + "_Week"
                + str(week): summ.loc[(twoyrago_yearterm,)][str(week)]
            }
        ),
    ],
    axis=1,
    sort=True,
)
tab_df = pd.concat(
    [
        tab_df,
        pd.DataFrame({last_yearterm + "_Total": summ.loc[(last_yearterm,)]["53"]}),
    ],
    axis=1,
    sort=True,
)
tab_df = pd.concat(
    [
        tab_df,
        pd.DataFrame(
            {twoyrago_yearterm + "_Total": summ.loc[(twoyrago_yearterm,)]["53"]}
        ),
    ],
    axis=1,
    sort=True,
)
tab_df = tab_df.fillna(0).astype(int)
print(tab_df.shape)
print(tab_df)
tab_df.head()

(87, 5)
                      2018.Fall_Week40  2017.Fall_Week40  2016.Fall_Week40  \
stage     curriculum
Accepted  AALM                       5                 5                 9
          BAKA                       3                 8                10
          BASM                       6                 7                15
          BIOG                       5                 6                11
          CASM                       9                10                12
          COMM                       2                 1                 2
          CULA                       0                 5                 7
          CULO                       2                 0                 0
          EBSB                       4                 5                 9
          ECOR                       7                 5                 1
          ENST                       3                 2                 2
          ENVS                      21                27                23
          FBIO                       1                 0                 3
          FEFM                       9                17                17
          FFOP                       8                 7                 9
          FORT                       4                 2                10
          FWSF                       8                13                17
          FWSW                      37                42                46
          HRMT                       1                 1                 1
          HRTM                       3                 5                 9
          INST                       1                 5                 3
          NRCM                      29                28                16
          PACM                      11                12                 7
          PSYCH                      1                 0                 0
          RECR                       7                 9                 8
          SCWL                       2                 2                 1
          SURV                       4                 6                 4
          UNDM                       0                 0                 0
          unknown                  644               658               507
Applied   AALM                       5                 5                10
...                                ...               ...               ...
          unknown                  655               676               545
Deposited AALM                       5                 5                10
          BAKA                       3                 5                 8
          BASM                       7                 7                14
          BIOG                       5                 3                 8
          CASM                      10                10                11
          COMM                       3                 1                 1
          CULA                       0                 4                 6
          CULO                       3                 0                 0
          EBSB                       5                 5                 5
          ECOR                       7                 5                 1
          ENST                       3                 2                 2
          ENVS                      21                21                25
          FBIO                       1                 0                 3
          FEFM                      10                16                20
          FFOP                       8                 7                 9
          FORT                       4                 2                 8
          FWSF                       9                13                17
          FWSW                      40                39                50
          HRMT                       1                 1                 1
          HRTM                       3                 6                 7
          INST                       2                 2                 2
          NRCM                      30                20                14
          PACM                      11                 8                 7
          PSYCH                      1                 0                 0
          RECR                       7                 9                 8
          SCWL                       2                 2                 1
          SURV                       4                 6                 2
          UNDM                       0                 0                 0
          unknown                    0                20                35

                      2017.Fall_Total  2016.Fall_Total
stage     curriculum
Accepted  AALM                      5                9
          BAKA                      8               11
          BASM                      8               15
          BIOG                      8               11
          CASM                     12               12
          COMM                      1                4
          CULA                      5                7
          CULO                      0                0
          EBSB                      5               10
          ECOR                      6                2
          ENST                      2                2
          ENVS                     28               24
          FBIO                      0                3
          FEFM                     19               20
          FFOP                      7                9
          FORT                      3               10
          FWSF                     13               17
          FWSW                     44               46
          HRMT                      1                1
          HRTM                      5               10
          INST                      5                3
          NRCM                     30               18
          PACM                     14               10
          PSYCH                     0                0
          RECR                     10                8
          SCWL                      5                1
          SURV                      7                4
          UNDM                      0                0
          unknown                 665              451
Applied   AALM                      5               11
...                               ...              ...
          unknown                 673              484
Deposited AALM                      5               11
          BAKA                      8               11
          BASM                      8               15
          BIOG                      8               11
          CASM                     13               14
          COMM                      1                4
          CULA                      5                8
          CULO                      0                0
          EBSB                      5               10
          ECOR                      6                2
          ENST                      2                2
          ENVS                     28               27
          FBIO                      0                3
          FEFM                     19               24
          FFOP                      7                9
          FORT                      4               10
          FWSF                     13               18
          FWSW                     45               51
          HRMT                      1                1
          HRTM                      6               10
          INST                      5                3
          NRCM                     30               18
          PACM                     15               10
          PSYCH                     0                0
          RECR                     10                8
          SCWL                      5                1
          SURV                      7                4
          UNDM                      1                0
          unknown                   2                1

[87 rows x 5 columns]

                     2018.Fall_Week40  2017.Fall_Week40  2016.Fall_Week40  \
stage    curriculum
Accepted AALM                       5                 5                 9
         BAKA                       3                 8                10
         BASM                       6                 7                15
         BIOG                       5                 6                11
         CASM                       9                10                12

                     2017.Fall_Total  2016.Fall_Total
stage    curriculum
Accepted AALM                      5                9
         BAKA                      8               11
         BASM                      8               15
         BIOG                      8               11
         CASM                     12               12

In [15]:
print(
    "2018.Fall",
    str(week),
    summ.loc[("2018.Fall", "Deposited")][str(week)].fillna(0).sum(),
)
print(
    "2017.Fall",
    str(week),
    summ.loc[("2017.Fall", "Deposited")][str(week)].fillna(0).sum(),
)

summ.loc[("2018.Fall", "Deposited")][str(week)] - summ.loc[("2017.Fall", "Deposited")][
    str(week)
]

2018.Fall 40 205
2017.Fall 40 219

curriculum
AALM        0.0
BAKA       -2.0
BASM        0.0
BIOG        2.0
CASM        0.0
COMM        2.0
CULA        NaN
CULO        NaN
EBSB        0.0
ECOR        2.0
ENST        1.0
ENVS        0.0
FBIO        NaN
FEFM       -6.0
FFOP        1.0
FORT        2.0
FWSF       -4.0
FWSW        1.0
HRMT        0.0
HRTM       -3.0
INST        0.0
NRCM       10.0
PACM        3.0
PSYCH       NaN
RECR       -2.0
SCWL        0.0
SURV       -2.0
UNDM        NaN
unknown   -20.0
Name: 40, dtype: float64

In [16]:
print("2017.Fall", "53", summ.loc[("2017.Fall", "Deposited")]["53"].sum())
print("2017.Fall", str(week), summ.loc[("2017.Fall", "Deposited")][str(week)].sum())

summ.loc[("2017.Fall", "Deposited")]["53"].sum() - summ.loc[("2017.Fall", "Deposited")][
    str(week)
].sum()

2017.Fall 53 259
2017.Fall 40 219

40

In [ ]:
weeks = range(0, 54)
for w in weeks:
    f = f"{w:02d}"
    yet_to_deposit = (
        summ.loc[("2017.Fall", "Deposited")]["53"]
        - summ.loc[("2017.Fall", "Deposited")][f]
    )
    print(w, yet_to_deposit)

In [17]:
summ.describe()

,00,01,02,03,04,05,06,07,08,09,...,44,45,46,47,48,49,50,51,52,53
count,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,...,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000
mean,0.612500,0.750000,0.850000,0.958333,1.108333,1.304167,1.654167,1.941667,2.554167,3.354167,...,24.212500,24.291667,24.362500,24.354167,24.425000,24.404167,24.183333,24.095833,24.008333,24.008333
std,2.700506,3.151011,3.731916,4.377378,5.363437,6.442795,7.887360,9.238627,12.097805,15.360507,...,95.398661,95.481769,95.532979,95.393238,95.432174,95.246823,94.133617,93.775187,93.308145,93.308145
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
max,36.000000,42.000000,51.000000,59.000000,74.000000,83.000000,96.000000,106.000000,117.000000,139.000000,...,688.000000,689.000000,689.000000,687.000000,688.000000,687.000000,675.000000,677.000000,673.000000,673.000000

In [18]:
summ.index

MultiIndex(levels=[['2016.Fall', '2017.Fall', '2018.Fall'], ['Accepted', 'Applied', 'Deposited'], ['AALM', 'BAKA', 'BASM', 'BIOG', 'CASM', 'COMM', 'CULA', 'CULO', 'EBSB', 'ECOR', 'ENST', 'ENVS', 'FBIO', 'FEFM', 'FFOP', 'FORT', 'FWSF', 'FWSW', 'HRMT', 'HRTM', 'INST', 'NRCM', 'PACM', 'PSYCH', 'RECR', 'SCWL', 'SURV', 'UNDM', 'unknown']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28]],
           names=['year_term', 'stage', 'curriculum'])

In [29]:
# from bokeh.layouts import widgetbox, row
# from bokeh.models.widgets import MultiSelect, RadioGroup, Select
# from bokeh.plotting import figure, curdoc
from bokeh.plotting import figure, output_file, show

# from bokeh.palettes import Blues9
from bokeh.palettes import Set2_8
from bokeh.io import output_notebook
from bokeh.layouts import widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

In [30]:
output_notebook()
output_file("Table_ByProgram.html")

In [31]:
stage = "Deposited"
title = f"'{stage}' By Program  {today_str}  (Week {adm_week_number:d})"

In [32]:
d = tab_df.loc[(stage,)]

In [33]:
source = ColumnDataSource(d)

In [54]:
columns = [
    TableColumn(field="curriculum", title="Program", width=100),
    TableColumn(
        field=this_yearterm + "_Week" + str(week),
        title=this_yearterm + "_Week" + str(week),
    ),
    TableColumn(
        field=last_yearterm + "_Week" + str(week),
        title=last_yearterm + "_Week" + str(week),
    ),
    TableColumn(
        field=twoyrago_yearterm + "_Week" + str(week),
        title=twoyrago_yearterm + "_Week" + str(week),
    ),
    TableColumn(field=last_yearterm + "_Total", title=last_yearterm + "_Total"),
    TableColumn(field=twoyrago_yearterm + "_Total", title=twoyrago_yearterm + "_Total"),
]
data_table = DataTable(
    source=source,
    columns=columns,
    width=600,
    height=600,
    index_position=None,
    reorderable=True,
    sortable=True,
)

In [55]:
show(widgetbox(data_table))